# Site settings for loopstate.dev
title: loopstate.dev
email: chris@loopstate.dev
description: >-
  Thoughts on DevOps, coding, music, and creative technology from a DevOps director
  who loves to code and curate playlists. Join me in exploring container orchestration,
  infrastructure automation, and the perfect soundtrack for deep work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://loopstate-dev.github.io" # the base hostname & protocol
logo: /assets/images/favicon.svg
tagline: code. flow. repeat.
author: Chris McFee

# Theme settings
favicon: /assets/images/favicon.svg
dark_mode: false # dark mode by default?

# SEO settings
twitter:
  username: loopstatedev
  card: summary_large_image

# Social links for the site
social:
  github: mickfeech
  linkedin: cmcfee
  #youtube: loopstatedev
  #tiktok: loopstatedev

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/
  playlists:
    output: true
    permalink: /playlists/:path/

# Pagination for blog
paginate: 9
paginate_path: "/blog/page:num/"

# Date format (used by post layout)
date_format: "%b %-d, %Y"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/blog/:title/"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "playlists"
    values:
      layout: "playlist"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md